---
- name: Update SystemMaxUse
  community.general.ini_file:
    dest: /etc/systemd/journald.conf
    section: Journal
    option: SystemMaxUse
    value: "{{ system_max_use }}"
    no_extra_spaces: yes
- name: Restart
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
