---
- name: Add chart repo
  kubernetes.core.helm_repository:
    name: gitlab
    url: https://charts.gitlab.io/
- name: Install
  kubernetes.core.helm:
    name: gitlab
    atomic: yes
    chart_ref: gitlab/gitlab
    create_namespace: yes
    namespace: gitlab
    update_repo_cache: yes
    wait: yes
    wait_timeout: 60m
    values:
      # Minimal settings
      global:
        ingress:
          configureCertmanager: false
          class: "nginx"
          annotations:
            kubernetes.io/tls-acme: "true"
        hosts:
          domain: "{{ domain }}"
        # Disable Rails bootsnap cache (temporary)
        rails:
          bootsnap:
            enabled: false
        shell:
          # Configure the clone link in the UI to include the high-numbered NodePort
          # value from below (`gitlab.gitlab-shell.service.nodePort`)
          port: 32022
      # Don't use certmanager, we'll self-sign
      certmanager:
        install: false
      # Use the `ingress` addon, not our Ingress (can't map 22/80/443)
      nginx-ingress:
        enabled: false
      # Save resources, only 3 CPU
      prometheus:
        install: false
      gitlab-runner:
        install: false
      # Reduce replica counts, reducing CPU & memory requirements
      gitlab:
        webservice:
          ingress:
            tls:
              secretName: gitlab-webservice-default-tls
          minReplicas: 1
          maxReplicas: 1
        sidekiq:
          minReplicas: 1
          maxReplicas: 1
        gitlab-shell:
          minReplicas: 1
          maxReplicas: 1
          # Map gitlab-shell to a high-numbered NodePort to support cloning over SSH since
          # Minikube takes port 22.
          service:
            type: NodePort
            nodePort: 32022
      registry:
        ingress:
          tls:
            secretName: gitlab-registry-tls
        hpa:
          minReplicas: 1
          maxReplicas: 1
      minio:
        ingress:
          tls:
            secretName: gitlab-minio-tls
