---
- name: Add chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    url: https://charts.bitnami.com/bitnami
- name: Install
  kubernetes.core.helm:
    name: argocd
    chart_ref: bitnami/argo-cd
    create_namespace: yes
    namespace: argocd
    update_repo_cache: yes
    values:
      config:
        secret:
          argocdServerAdminPassword: '{{ lookup("community.general.passwordstore", "{{ key_name }} create=true length=20") }}'
      server:
        extraArgs:
          - --insecure
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hostname: "argocd.{{ domain }}"
          tls: true