---
- hosts: default
  gather_facts: no
  pre_tasks:
    - name: Refresh snap
      ansible.builtin.shell:
        cmd: snap refresh
    - name: Install snap packages
      community.general.snap:
        name: "{{ item }}"
      with_items:
        - docker
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes
    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
      with_items:
        - ncdu
        - python3-pip
    - name: Install kubernetes package
      ansible.builtin.pip:
        name: "{{ item }}"
      with_items:
        - openshift
  roles:
    - journald
    - role: frpc
      vars:
        key_name: cysista-proxy/frps
    - microk8s
    - ingress-nginx
    - cert-manager
    - role: kube-prometheus-stack
      vars:
        key_name: cysista-develop/kube-prometheus-stack
    - role: argo-cd
      vars:
        key_name: cysista-develop/argo-cd
        redis_key_name: cysista-develop/argo-cd-redis
    - role: wordpress
      vars:
        key_name: cysista-develop/wordpress
        db_root_key_name: cysista-develop/wordpress-db-root
        db_key_name: cysista-develop/wordpress-db
    - role: gitea
      vars:
        key_name: cysista-develop/gitea
        email_key_name: cysista-develop/email
