---
- hosts: default
  gather_facts: no
  pre_tasks:
    - name: Refresh snap
      ansible.builtin.shell:
        cmd: snap refresh
    - name: Install snap packages
      community.general.snap:
        name: "{{ item }}"
      with_items:
        - docker
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: yes
    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
      with_items:
        - ncdu
        - python3-pip
    - name: Install kubernetes package
      ansible.builtin.pip:
        name: "{{ item }}"
      with_items:
        - openshift
  roles:
    - role: frpc
      vars:
        key_name: cysista-proxy/frps
        frpc_ini_file: frpc.ini.j2
    - microk8s
    - ingress-nginx
    - cert-manager
    - kube-prometheus-stack
    - gitlab
    - argo-cd
