---
- name: Add chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    url: https://charts.bitnami.com/bitnami
- name: Install
  kubernetes.core.helm:
    name: wordpress
    chart_ref: bitnami/wordpress
    chart_version: 12.3.3
    create_namespace: yes
    namespace: wordpress
    update_repo_cache: yes
    values:
      wordpressPassword: '{{ lookup("community.general.passwordstore", "{{ key_name }} create=true length=20") }}'
      service:
        type: ClusterIP
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
        hostname: "wordpress.{{ domain }}"
        tls: true
      mariadb:
        auth:
          rootPassword: '{{ lookup("community.general.passwordstore", "{{ db_root_key_name }} create=true length=20") }}'
          password: '{{ lookup("community.general.passwordstore", "{{ db_key_name }} create=true length=20") }}'
