---
- name: Add chart repo
  kubernetes.core.helm_repository:
    name: gitea-charts
    url: https://dl.gitea.io/charts/
- name: Install
  kubernetes.core.helm:
    name: gitea
    chart_ref: gitea-charts/gitea
    chart_version: 5.0.9
    create_namespace: yes
    namespace: gitea
    update_repo_cache: yes
    values:
      gitea:
        admin:
          existingSecret:
          # gitea_admin以外にするとエラーになるっぽい
          username: gitea_admin
          password: '{{ lookup("community.general.passwordstore", "{{ key_name }} create=true length=20") }}'
          email: "{{ email }}"
        config:
          service:
            REGISTER_EMAIL_CONFIRM: true
            # TODO ドメインと一致されるようにする
            EMAIL_DOMAIN_WHITELIST: cysista.co.jp
          mailer:
            # 安全性の低いアプリのアクセスを許可にする必要がある
            ENABLED: true
            HOST: smtp.gmail.com:465
            FROM: "{{ email }}"
            USER: "{{ email }}"
            PASSWD: '{{ lookup("community.general.passwordstore", "{{ email_key_name }}") }}'
            MAILER_TYPE: smtp
            IS_TLS_ENABLED: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: "gitea.{{ domain }}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: gitea-tls
            hosts:
              - "gitea.{{ domain }}"